language: php
php:
  - 7.2
  - 7.1
  - 7.0

dist: trusty
sudo: required

services:
  - mysql
  - redis-server

before_script:
  - echo -e "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
  - mysql -e 'create database mydb;'
  - php vendor/bin/phinx migrate

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls

notifications:
  email: false