language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

sudo: false

before_script:
    - composer install
    - mysql -e 'create database mydb;'
    - php vendor/bin/phinx migrate

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls